### ISSUE TITLE
How do you open this project in IntelliJ CE

### ISSUE THREAD

**Issue by simon-tse-hs** [elpassion/react.kt#1]
I'm trying to open or import the project into IntelliJ CE and either opens but can't see the source code in the explorer or it doesn't know how to import as a gradle project.
What tooling of Intellig or setup do you have?

**Comment by pawegio** [comment]
Hi, we used IntelliJ Ultimate Edition to run the project. According to [this comparison matrix](https://www.jetbrains.com/idea/features/editions_comparison_matrix.html) react is not supported in Community Edition. Project should also open in WebStorm.
